meta_product_name: "Not Alone"
meta_title: "Not Alone - Change a child's life today"
meta_description: "Join Not Alone as a volunteer and help children dealing with traumatic experiences heal"
meta_image: "bannerpic.jpg" # should exist in `app/assets/images/`
